# 03 - Trigger: pull_request
# Runs when a Pull Request is opened, updated (new commits), or reopened.
# Use this to test code BEFORE it is merged into your main branch.

name: PRTrigger
on:
  pull_request:
jobs:
  created-PR:
    runs-on: ubuntu:latest
    steps:
      - name: Let-to-merge
        run: | 
          echo "Please review the following PR And"
          echo "Approve the PR"
