name : env-scopes
on: workflow_dispatch
env:
  stage: workflow-level
jobs:
  job 1:
    runs-on: ubuntu-latest
    steps:
      - name: workflow scope
        run: echo "job1 run on stage $stage"
      - name: stage scope
        env:
          stage: stage-level
         run: echo "STAGE = $stage"
  job2:
    runs-on: ubuntu-latest
    env:
      stage: job-level
    steps:
      - name: job scope
        run:  echo "job2 runs on $stage"
      - name: Read env var
        if: ${{env.stage == 'job-level'}}  
        run: |
          echo "Express saw STAGE = ${{env.stage}}"
          
