name: 16-composite
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 
  
      - name: install 21 version
        uses: ./.github/actions/build
        with:
          JavaVersion: 21
      
      - name: install 25
        uses: ./.github/actions/build
        with:
           JavaVersion: 25

  matrixJob:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        java: [11,17,8]
    steps:
      - name: install java
        uses:  ./.github/actions/build
        with:
          JavaVersion: ${{matrix.java}}
  
