name: jsonview
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: print github respo
        run: ${{toJson(github)}}

      - name: print runner
        run: ${{toJson(runner)}}
